---
services: [docker]
language: python
env:
  global:
    - |
      RELEASE_DEBUG="" \
      DO_RELEASE="1" \
      RELEASABLE_REPOS="corpusops/" \
      COPS_URL="https://github.com/corpusops/corpusops.bootstrap" \
      COPS_ROOT="$TRAVIS_BUILD_DIR/local/corpusops.bootstrap" \
      funcs="$COPS_ROOT/bin/cops_shell_common" \
      silent="$funcs output_in_error silent_vv" \
      apply_role="sudo -E $silent $COPS_ROOT/bin/cops_apply_role -vvvvv" \
      install="sudo -E $silent $COPS_ROOT/bin/install.sh" \
      sync_code="$install -C --synchronize-code --skip-sync-core" \
      release="$COPS_ROOT/hacking/docker_release" \
      silent_rm="$silent rm -rf"
  matrix:
  - IMAGES="library/alpine/latest library/alpine/3.1 library/alpine/3.2 library/alpine/3.3 library/alpine/3.4 library/alpine/3.5 library/alpine/3.6 library/alpine/3.7 library/alpine/3.8 library/postgres/alpine library/postgres/11-alpine library/postgres/10-alpine mdillon/postgis/11-alpine mdillon/postgis/10-alpine library/traefik/alpine library/nginx/alpine-perl library/nginx/mainline-alpine-perl library/nginx/stable-alpine-perl library/nginx/alpine library/nginx/mainline-alpine library/nginx/stable-alpine library/node/alpine library/node/lts-alpine library/node/10-alpine library/node/11-alpine library/ruby/alpine library/ruby/2-alpine library/ruby/2.3-alpine library/ruby/2.5-alpine library/php/alpine library/php/cli-alpine library/php/fpm-alpine library/php/zts-alpine library/php/5-alpine library/php/5-cli-alpine library/php/5-fpm-alpine library/php/5-zts-alpine library/php/7-alpine library/php/7-cli-alpine library/php/7-fpm-alpine library/php/7-zts-alpine library/php/7.3-alpine library/php/7.3-cli-alpine library/php/7.3-fpm-alpine library/php/7.3-zts-alpine library/elasticsearch/5-alpine library/elasticsearch/6.5.4 library/elasticsearch/6.5.3 library/elasticsearch/6.5.2 library/elasticsearch/6.5.1 library/elasticsearch/6.5.0 library/solr/alpine library/redis/alpine library/redis/5.0-alpine library/redis/5-alpine library/redis/4.0-alpine library/redis/4-alpine minio/minio/edge minio/minio/latest minio/mint/1.0.0 minio/mint/edge minio/mint/latest mailhog/mailhog/latest library/solr/7-alpine"
  - IMAGES="library/debian/latest library/debian/sid library/debian/sid-slim library/debian/9 library/debian/9-slim library/debian/stable library/debian/stable-slim library/debian/7-slim library/debian/8-slim library/debian/7 library/debian/8 library/centos/latest library/centos/7 library/nginx/latest library/nginx/perl library/nginx/mainline library/nginx/mainline-perl library/nginx/stable library/nginx/stable-perl library/elasticsearch/6.4.3 library/elasticsearch/6.4.2 library/elasticsearch/6.4.1 library/elasticsearch/6.4.0 library/elasticsearch/1 minio/doctor/latest minio/k8s-operator/latest minio/mc/edge minio/mc/latest library/elasticsearch/2"
  - IMAGES="library/ubuntu/latest library/ubuntu/bionic library/ubuntu/18.04 library/ubuntu/16.04 library/ubuntu/xenial library/ubuntu/14.04 library/ubuntu/trusty library/solr/latest library/solr/7 library/solr/7-slim library/mysql/8 library/mysql/5 library/redis/stretch library/redis/latest library/redis/5.0-stretch library/redis/5.0 library/redis/5-stretch library/redis/5 library/redis/4.0-stretch library/redis/4.0 library/redis/4-stretch library/redis/4 library/mongo/latest library/mongo/4"
  - IMAGES="library/postgres/latest mdillon/postgis/latest library/postgres/11 makinacorpus/pgrouting/10.1-2.5.4 library/postgres/10 library/postgres/9 mdillon/postgis/11 mdillon/postgis/10 mdillon/postgis/9.0 mdillon/postgis/9.1 mdillon/postgis/9.2 mdillon/postgis/9.2-alpine mdillon/postgis/9.3 mdillon/postgis/9.3-alpine mdillon/postgis/9.4 mdillon/postgis/9.4-alpine mdillon/postgis/9.5 mdillon/postgis/9.5-alpine mdillon/postgis/9.6 mdillon/postgis/9.6-alpine library/mysql/latest library/elasticsearch/5 library/mongo/3 library/solr/6 library/solr/6-slim"
  - IMAGES="library/golang/latest library/python/3 library/python/2 library/python/latest library/python/3.7 library/python/3.6 library/node/latest library/node/slim library/node/lts library/node/lts-slim library/node/11 library/node/11-slim library/node/10 library/node/10-slim library/node/9 library/node/9-slim library/node/8 library/node/8-slim library/node/7 library/node/7-slim library/solr/5-slim library/solr/5 library/mongo/2"
  - IMAGES="library/php/7 library/php/7-cli library/php/7-fpm library/php/7-zts library/php/5 library/php/5-cli library/php/5-fpm library/php/5-zts library/php/latest library/php/cli library/php/fpm library/php/zts library/php/7.3 library/php/7.3-cli library/php/7.3-fpm library/php/7.3-zts library/php/7.2 library/php/7.2-cli library/php/7.2-fpm library/php/7.2-zts"
  - IMAGES="library/php/5.6 library/php/5.6-cli library/php/5.6-fpm library/php/5.6-zts library/php/7.0 library/php/7.0-cli library/php/7.0-fpm library/php/7.0-zts library/php/7.1 library/php/7.1-cli library/php/7.1-fpm library/php/7.1-zts"
  - IMAGES="library/ruby/latest library/ruby/slim library/ruby/2 library/ruby/2-slim library/ruby/2.5 library/ruby/2.5-slim library/ruby/2.4 library/ruby/2.4-slim library/ruby/2.3 library/ruby/2.3-slim library/ruby/2.1 library/ruby/2.1-slim library/ruby/2.2 library/ruby/2.2-slim library/ruby/1 library/ruby/1-slim library/ruby/1.9 library/ruby/1.9-slim"
  - IMAGES="library/ruby/2.4-alpine library/postgres/9-alpine library/php/5.6-alpine library/php/5.6-cli-alpine library/php/5.6-fpm-alpine library/php/5.6-zts-alpine library/solr/6-alpine library/node/7-alpine library/node/8-alpine library/node/9-alpine library/ruby/2.1-alpine library/ruby/2.2-alpine library/php/7.0-alpine library/php/7.0-cli-alpine library/php/7.0-fpm-alpine library/php/7.0-zts-alpine library/php/7.1-alpine library/php/7.1-cli-alpine library/php/7.1-fpm-alpine library/php/7.1-zts-alpine library/php/7.2-alpine library/php/7.2-cli-alpine library/php/7.2-fpm-alpine library/php/7.2-zts-alpine library/solr/5-alpine library/elasticsearch/1-alpine library/elasticsearch/2-alpine"
# all images that werent explicitly told to be built would be built in the next batches
# we span them onto N jobs
  - IMAGES="leftover:1/46"
  - IMAGES="leftover:2/46"
  - IMAGES="leftover:3/46"
  - IMAGES="leftover:4/46"
  - IMAGES="leftover:5/46"
  - IMAGES="leftover:6/46"
  - IMAGES="leftover:7/46"
  - IMAGES="leftover:8/46"
  - IMAGES="leftover:9/46"
  - IMAGES="leftover:10/46"
  - IMAGES="leftover:11/46"
  - IMAGES="leftover:12/46"
  - IMAGES="leftover:13/46"
  - IMAGES="leftover:14/46"
  - IMAGES="leftover:15/46"
  - IMAGES="leftover:16/46"
  - IMAGES="leftover:17/46"
  - IMAGES="leftover:18/46"
  - IMAGES="leftover:19/46"
  - IMAGES="leftover:20/46"
  - IMAGES="leftover:21/46"
  - IMAGES="leftover:22/46"
  - IMAGES="leftover:23/46"
  - IMAGES="leftover:24/46"
  - IMAGES="leftover:25/46"
  - IMAGES="leftover:26/46"
  - IMAGES="leftover:27/46"
  - IMAGES="leftover:28/46"
  - IMAGES="leftover:29/46"
  - IMAGES="leftover:30/46"
  - IMAGES="leftover:31/46"
  - IMAGES="leftover:32/46"
  - IMAGES="leftover:33/46"
  - IMAGES="leftover:34/46"
  - IMAGES="leftover:35/46"
  - IMAGES="leftover:36/46"
  - IMAGES="leftover:37/46"
  - IMAGES="leftover:38/46"
  - IMAGES="leftover:39/46"
  - IMAGES="leftover:40/46"
  - IMAGES="leftover:41/46"
  - IMAGES="leftover:42/46"
  - IMAGES="leftover:43/46"
  - IMAGES="leftover:44/46"
  - IMAGES="leftover:45/46"
  - IMAGES="leftover:46/46"
cache: {directories: ["$HOME/.cache/pip", "$COPS_ROOT"]}
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y --force-yes parallel
- sudo service docker stop
- ./main.sh refresh_corpusops
- sh -c "$apply_role */*/roles/corpusops.roles/services_virt_docker/role.yml"
- i=$(whoami) && sudo chown -Rf $i $COPS_ROOT
script:
- echo "building $IMAGES" >&2
# for any released tags from where we did our last maintenance, get a chance to discover and build it
- cd "$TRAVIS_BUILD_DIR" && if ( echo $IMAGES | grep -q leftover );then  $silent ./refresh_images.sh;fi
- cd "$TRAVIS_BUILD_DIR" && export DO_RELEASE=1 && $silent ./build.sh $IMAGES
