---
services: [docker]
language: python
env:
  global:
    - |
      RELEASE_DEBUG="" \
      DO_RELEASE="1" \
      RELEASABLE_REPOS="corpusops/" \
      COPS_URL="https://github.com/corpusops/corpusops.bootstrap" \
      COPS_ROOT="$TRAVIS_BUILD_DIR/local/corpusops.bootstrap" \
      funcs="$COPS_ROOT/bin/cops_shell_common" \
      silent="$funcs output_in_error silent_vv" \
      apply_role="sudo -E $silent $COPS_ROOT/bin/cops_apply_role -vvvvv" \
      install="sudo -E $silent $COPS_ROOT/bin/install.sh" \
      sync_code="$install -C --synchronize-code --skip-sync-core" \
      release="$COPS_ROOT/hacking/docker_release" \
      silent_rm="$silent rm -rf"
  matrix:
  - IMAGES="library/postgres/alpine library/postgres/11-alpine library/postgres/10-alpine library/postgres/9-alpine mdillon/postgis/11-alpine mdillon/postgis/10-alpine library/traefik/alpine library/nginx/alpine-perl library/nginx/mainline-alpine-perl library/nginx/stable-alpine-perl library/nginx/alpine library/nginx/mainline-alpine library/nginx/stable-alpine library/node/alpine library/node/lts-alpine library/node/7-alpine library/node/8-alpine library/node/9-alpine library/node/10-alpine library/node/11-alpine library/ruby/alpine library/ruby/2-alpine library/ruby/2.1-alpine library/ruby/2.2-alpine library/ruby/2.3-alpine library/ruby/2.4-alpine library/ruby/2.5-alpine library/php/alpine library/php/cli-alpine library/php/fpm-alpine library/php/zts-alpine library/php/5-alpine library/php/5-cli-alpine"
  - IMAGES="library/php/5-fpm-alpine library/php/5-zts-alpine library/php/5.6-alpine library/php/5.6-cli-alpine library/php/5.6-fpm-alpine library/php/5.6-zts-alpine library/php/7-alpine library/php/7-cli-alpine library/php/7-fpm-alpine library/php/7-zts-alpine library/php/7.0-alpine library/php/7.0-cli-alpine library/php/7.0-fpm-alpine library/php/7.0-zts-alpine library/php/7.1-alpine library/php/7.1-cli-alpine library/php/7.1-fpm-alpine library/php/7.1-zts-alpine library/php/7.2-alpine library/php/7.2-cli-alpine library/php/7.2-fpm-alpine library/php/7.2-zts-alpine library/php/7.3-alpine library/php/7.3-cli-alpine library/php/7.3-fpm-alpine library/php/7.3-zts-alpine library/solr/alpine library/solr/7-alpine library/solr/6-alpine library/solr/5-alpine library/elasticsearch/1-alpine library/elasticsearch/2-alpine library/elasticsearch/5-alpine"
  - IMAGES="library/ubuntu/latest library/ubuntu/18.04 library/ubuntu/16.04 library/ubuntu/14.04 library/ubuntu/trusty library/ubuntu/xenial library/python/3 library/python/3.6 library/python/3.7 library/python/2 library/node/latest library/golang/latest library/alpine/latest library/centos/latest library/centos/7 library/debian/latest library/debian/7-slim"
  - IMAGES="library/debian/8-slim library/debian/9-slim library/debian/7 library/debian/8 library/debian/9 library/debian/sid-slim library/debian/stable-slim library/debian/sid library/debian/stable makinacorpus/pgrouting/10.1-2.5.4 library/mysql/5 library/mysql/8 library/mysql/latest library/postgres/latest library/postgres/11 library/postgres/10 library/postgres/9"
  - IMAGES="mdillon/postgis/latest mdillon/postgis/11 mdillon/postgis/10 mdillon/postgis/9.0 mdillon/postgis/9.1 mdillon/postgis/9.2 mdillon/postgis/9.2-alpine mdillon/postgis/9.3 mdillon/postgis/9.3-alpine mdillon/postgis/9.4 mdillon/postgis/9.4-alpine mdillon/postgis/9.5 mdillon/postgis/9.5-alpine mdillon/postgis/9.6 mdillon/postgis/9.6-alpine library/nginx/perl library/nginx/mainline-perl"
  - IMAGES="library/nginx/stable-perl library/nginx/latest library/nginx/mainline library/nginx/stable library/node/latest library/node/lts library/node/slim library/node/7 library/node/8 library/node/9 library/node/10 library/node/11 library/node/slim library/node/lts-slim library/node/7-slim library/node/8-slim library/node/9-slim"
  - IMAGES="library/node/10-slim library/node/11-slim library/ruby/latest library/ruby/1 library/ruby/1.9 library/ruby/2 library/ruby/2.1 library/ruby/2.2 library/ruby/2.3 library/ruby/2.4 library/ruby/2.5 library/ruby/slim library/ruby/1-slim library/ruby/1.9-slim library/ruby/2-slim library/ruby/2.1-slim library/ruby/2.2-slim"
  - IMAGES="library/ruby/2.3-slim library/ruby/2.4-slim library/ruby/2.5-slim library/php/latest library/php/cli library/php/fpm library/php/zts library/php/5 library/php/5-cli library/php/5-fpm library/php/5-zts library/php/5.6 library/php/5.6-cli library/php/5.6-fpm library/php/5.6-zts library/php/7 library/php/7-cli"
  - IMAGES="library/php/7-fpm library/php/7-zts library/php/7.0 library/php/7.0-cli library/php/7.0-fpm library/php/7.0-zts library/php/7.1 library/php/7.1-cli library/php/7.1-fpm library/php/7.1-zts library/php/7.2 library/php/7.2-cli library/php/7.2-fpm library/php/7.2-zts library/php/7.3 library/php/7.3-cli library/php/7.3-fpm"
  - IMAGES="library/php/7.3-zts library/solr/latest library/solr/7 library/solr/6 library/solr/5 library/solr/7-slim library/solr/6-slim library/solr/5-slim library/mongo/latest library/mongo/2 library/mongo/3 library/mongo/4 library/elasticsearch/1 library/elasticsearch/2 library/elasticsearch/5"
# all images that werent explicitly told to be built would be built in the next batches
# we split them into 8 jobs
  - IMAGES="leftover:1/8"
  - IMAGES="leftover:2/8"
  - IMAGES="leftover:3/8"
  - IMAGES="leftover:4/8"
  - IMAGES="leftover:5/8"
  - IMAGES="leftover:6/8"
  - IMAGES="leftover:7/8"
  - IMAGES="leftover:8/8"
cache: {directories: ["$HOME/.cache/pip", "$COPS_ROOT"]}
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y --force-yes parallel
- sudo service docker stop
- ./main.sh refresh_corpusops
- sh -c "$apply_role */*/roles/corpusops.roles/services_virt_docker/role.yml"
- i=$(whoami) && sudo chown -Rf $i $COPS_ROOT
script:
- echo "building $IMAGES" >&2
# for any released tags from where we did our last maintenance, get a chance to discover and build it
- cd "$TRAVIS_BUILD_DIR" && if ( echo $IMAGES | grep -q leftover );then  $silent ./refresh_images.sh;fi
- cd "$TRAVIS_BUILD_DIR" && export DO_RELEASE=1 && $silent ./build.sh $IMAGES
