ADD helpers/${SYSTEM}_clean.sh /tmp/corpusopssteroids/
RUN sh -c 'set -ex \
    && cd /tmp/corpusopssteroids \
    && chmod +x *sh \
    && ./${SYSTEM}_clean.sh \
    && cd / && rm -rf /tmp/corpusopssteroids'
