ADD helpers/system_detect.sh helpers/*_clean.sh /tmp/corpusopssteroids/
RUN sh -c 'set -ex \
    && echo fixperms >&2 \
    && ( chmod -vf g-wx,o-wx /etc/logrotate.d/* /etc/logrotate.conf || true ) \
    && echo cleanup >&2 \
    && cd /tmp/corpusopssteroids \
    && chmod +x *sh \
    && _cops_SYSTEM=$(./system_detect.sh) \
    && ./${_cops_SYSTEM}_clean.sh \
    && ./common_clean.sh \
    && cd / && rm -rf /tmp/corpusopssteroids /var/cache/apk/* /var/lib/apt/lists/*'
