RUN sh -c 'set -ex \
    && cd /tmp/corpusopssteroids \
    && chmod +x *sh \
    && cat optional_packages_*.txt > optional_packages.txt \
    && cat packages_*.txt > packages.txt \
    && ./${_cops_SYSTEM}_up.sh \
    && cp -v cops_pkgmgr_install.sh /bin \
    && ./add_opt_pkgs.sh \
    && DEBUG=1 ./setup_locales.sh \
    && ./add_dockerize.sh \
    && ./add_gosu.sh \
    && ./add_forego.sh \
    '
COPY --from=ochinchina/supervisord:latest \
    /usr/local/bin/supervisord /bin/supervisord-go
