env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  BUILDKIT_PROGRESS: "plain"
  NO_SQUASH: ""
  NO_SILENT: "1"
  NONINTERACTIVE: "1"
  FORCE_ONLINE: "1"
  NBPARALLEL: "2"
  RELEASABLE_REPOS: "^corpusops/"
  RELEASABLE_BRANCHES: "^(refs/heads/)?(master|2.0|workflows)$"
  COPS_URL: "https://github.com/corpusops/corpusops.bootstrap"
  COPS_ROOT: "${{github.workspace}}/local/corpusops.bootstrap"
  silent: "$COPS_ROOT/bin/cops_shell_common output_in_error silent_vv"
  DOCKER_RELEASER: "${{ secrets.DOCKER_HUB_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
jobs:
  r:
    runs-on: ubuntu-20.04
    env: {IMAGES: "${{matrix.IMAGES}}"}
    steps:
      - name: Set vars
        run: |-
            if ( echo "$GITHUB_REF" | egrep -q "${RELEASABLE_BRANCHES}" ) \
            && ( echo "$GITHUB_REPOSITORY" | egrep -q "${RELEASABLE_REPOS}" )
            then releasable=true;else releasable=false;fi
            echo "::set-output name=releasable::$releasable"
            echo "::set-output name=silent::$(echo $silent)"
        id: v
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Activate docker experimental
        run: |-
          sudo bash -exc "service docker stop;python -c \
          \"d='/etc/docker/daemon.json';\
          import json;c=json.load(open(d));c['experimental']=True;\
          open(d, 'w').write(json.dumps(c))\"
          systemctl restart docker"
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            local
          key: 6-${{ runner.os }}-${{ github.ref }}-${{ github.repository }}-venvstatics
      - name: setup
        run: set -e;i=$(whoami);sudo sh -c "chown -Rf $i .";
             ./main.sh refresh_corpusops;
             sudo sh -c 'apt-get update -qq && apt-get install -qqy --force-yes parallel'
      - name: refresh images
        run: set -e;if (echo $IMAGES|grep -q zleftover);then
             rm -f */*/*/Dockerfile&&${{steps.v.outputs.silent}} ./refresh_images.sh;
             fi
      - name: build & release
        run: set -e;
             if [ "x${{steps.v.outputs.releasable}}" = "xtrue" ];then export DO_RELEASE=1;fi;
             ./build.sh $IMAGES
# ${{steps.v.outputs.silent}} ./build.sh $IMAGES
    strategy:
      fail-fast: false
      matrix:
        IMAGES:
        - "library/ubuntu/latest library/ubuntu/focal library/ubuntu/bionic library/ubuntu/20.04 library/ubuntu/18.04 library/ubuntu/16.04 library/ubuntu/xenial library/ubuntu/14.04 library/ubuntu/trusty library/solr/latest library/solr/7 library/solr/7-slim library/mysql/8 library/mysql/5 library/rabbitmq/3 library/rabbitmq/3-alpine library/rabbitmq/3-management library/rabbitmq/3-management-alpine library/rabbitmq/alpine library/rabbitmq/latest library/rabbitmq/management library/rabbitmq/management-alpine library/redis/stretch library/redis/latest library/redis/5-stretch library/redis/5 library/redis/4-stretch library/redis/4 library/memcached/latest library/memcached/alpine library/mongo/latest library/mongo/4"
        - "library/alpine/latest library/alpine/3 mailu/rspamd/1.7 mailu/rspamd/latest mailu/rspamd/master mailu/postfix/1.7 mailu/postfix/latest mailu/postfix/master library/postgres/alpine library/postgres/12-alpine library/postgres/13-alpine library/postgres/11-alpine library/postgres/10-alpine corpusops/postgis-bare/alpine corpusops/postgis-bare/11-alpine corpusops/postgis-bare/10-alpine library/traefik/alpine library/nginx/1-alpine library/nginx/1.15-alpine library/nginx/1.14-alpine library/nginx/alpine-perl library/nginx/mainline-alpine-perl library/nginx/stable-alpine-perl library/nginx/alpine library/nginx/mainline-alpine library/nginx/stable-alpine library/node/alpine library/node/lts-alpine library/node/12-alpine library/node/13-alpine library/ruby/alpine library/ruby/2-alpine library/ruby/2.3-alpine library/ruby/2.5-alpine"
        - "library/php/alpine library/php/cli-alpine library/php/fpm-alpine library/php/zts-alpine library/php/5-alpine library/php/5-cli-alpine library/php/5-fpm-alpine library/php/5-zts-alpine library/php/7-alpine library/php/7-cli-alpine library/php/7-fpm-alpine library/php/7-zts-alpine library/php/7.3-alpine library/php/7.3-cli-alpine library/php/7.3-fpm-alpine library/php/7.3-zts-alpine library/elasticsearch/5-alpine library/elasticsearch/6.5.4 library/elasticsearch/6.5.3 library/elasticsearch/6.5.2 library/elasticsearch/6.5.1 library/elasticsearch/6.5.0 library/solr/alpine library/redis/alpine library/redis/5-alpine library/redis/4-alpine minio/minio/edge minio/minio/latest mailhog/mailhog/latest library/solr/7-alpine"
        - "library/debian/latest library/debian/sid library/debian/sid-slim library/debian/9 library/debian/9-slim library/debian/stable library/debian/stable-slim library/debian/7-slim library/debian/8-slim library/debian/7 library/debian/8 library/centos/latest library/centos/7 library/nginx/latest library/nginx/perl library/nginx/mainline library/nginx/mainline-perl"
        - "library/nginx/stable library/nginx/stable-perl library/elasticsearch/6.4.3 library/elasticsearch/6.4.2 library/elasticsearch/6.4.1 library/elasticsearch/6.4.0 library/elasticsearch/1 minio/doctor/latest minio/mc/edge minio/mc/latest library/elasticsearch/2"
        - "library/postgres/latest corpusops/postgis-bare/latest library/postgres/12 library/postgres/13 library/postgres/11 library/postgres/10 library/postgres/9 corpusops/postgis-bare/11 corpusops/postgis-bare/10 corpusops/postgis-bare/9 library/mysql/latest library/elasticsearch/5 library/mongo/3 library/solr/6 library/solr/6-slim library/mariadb/latest library/mariadb/10 library/mariadb/10.1 library/mariadb/10.2 library/mariadb/10.3 library/mariadb/10.4 library/archlinux/latest"
        - "library/golang/latest library/python/3 library/python/2 library/python/latest library/python/3.7 library/python/3.6 library/node/latest library/node/slim library/node/lts library/node/lts-slim library/node/11 library/node/11-slim library/node/10 library/node/10-slim library/node/9 library/node/9-slim library/node/8 library/node/8-slim library/node/7 library/node/7-slim library/solr/5-slim library/solr/5 library/mongo/2"
        - "library/php/7 library/php/7-cli library/php/7-fpm library/php/7-zts library/php/5 library/php/5-cli library/php/5-fpm library/php/5-zts library/php/latest library/php/cli library/php/fpm library/php/zts library/php/7.3 library/php/7.3-cli library/php/7.3-fpm library/php/7.3-zts library/php/7.2 library/php/7.2-cli library/php/7.2-fpm library/php/7.2-zts"
        - "library/php/5.6 library/php/5.6-cli library/php/5.6-fpm library/php/5.6-zts library/php/7.0 library/php/7.0-cli library/php/7.0-fpm library/php/7.0-zts library/php/7.1 library/php/7.1-cli library/php/7.1-fpm library/php/7.1-zts"
        - "library/ruby/latest library/ruby/slim library/ruby/2 library/ruby/2-slim library/ruby/2.5 library/ruby/2.5-slim library/ruby/2.4 library/ruby/2.4-slim library/ruby/2.3 library/ruby/2.3-slim library/ruby/2.1 library/ruby/2.1-slim library/ruby/2.2 library/ruby/2.2-slim library/ruby/1 library/ruby/1-slim library/ruby/1.9 corpusops/pgrouting-bare/latest corpusops/pgrouting-bare/10 corpusops/pgrouting-bare/11 corpusops/pgrouting-bare/11-2.5 corpusops/pgrouting-bare/9.6-2.5-2.6 corpusops/pgrouting-bare/9.6-2.5 corpusops/pgrouting-bare/9.6-2.4-2.6 corpusops/pgrouting-bare/9.6-2.4 corpusops/pgrouting-bare/9.6 corpusops/pgrouting-bare/11-2.5-2.6 corpusops/pgrouting-bare/10-2.5-2.6 corpusops/pgrouting-bare/10-2.5 corpusops/pgrouting-bare/10-2.4-2.6 corpusops/pgrouting-bare/10-2.4 library/ruby/1.9-slim"
        - "library/ruby/2.4-alpine library/postgres/9-alpine corpusops/postgis-bare/9-alpine library/php/5.6-alpine library/php/5.6-cli-alpine library/php/5.6-fpm-alpine library/php/5.6-zts-alpine library/solr/6-alpine library/node/7-alpine library/node/8-alpine library/node/9-alpine library/ruby/2.1-alpine"
        - "library/ruby/2.2-alpine library/php/7.0-alpine library/php/7.0-cli-alpine library/php/7.0-fpm-alpine library/php/7.0-zts-alpine library/php/7.1-alpine library/php/7.1-cli-alpine library/php/7.1-fpm-alpine library/php/7.1-zts-alpine library/php/7.2-alpine library/php/7.2-cli-alpine library/php/7.2-fpm-alpine"
        - "library/php/7.2-zts-alpine library/solr/5-alpine library/elasticsearch/1-alpine library/elasticsearch/2-alpine seafileltd/seafile-mc/7.1.4"
        - "library/docker/dind library/docker/dind-rootless library/docker/edge library/docker/edge-dind library/docker/experimental library/docker/experimental-dind library/docker/git library/docker/latest library/docker/rc library/docker/rc-dind library/docker/rc-dind-rootless library/docker/rc-experimental library/docker/rc-experimental-dind library/docker/stable library/docker/stable-dind library/docker/stable-dind-rootless library/docker/test library/docker/test-dind library/docker/test-dind-rootless library/redmine/4-passenger"
        #- "corpusops/test/a corpusops/test/b corpusops/test/c"
        # all images that werent explicitly told to be built would be built in the next batches
        # we span them onto N jobs
        - "zleftover:1/91"
        - "zleftover:2/91"
        - "zleftover:3/91"
        - "zleftover:4/91"
        - "zleftover:5/91"
        - "zleftover:6/91"
        - "zleftover:7/91"
        - "zleftover:8/91"
        - "zleftover:9/91"
        - "zleftover:10/91"
        - "zleftover:11/91"
        - "zleftover:12/91"
        - "zleftover:13/91"
        - "zleftover:14/91"
        - "zleftover:15/91"
        - "zleftover:16/91"
        - "zleftover:17/91"
        - "zleftover:18/91"
        - "zleftover:19/91"
        - "zleftover:20/91"
        - "zleftover:21/91"
        - "zleftover:22/91"
        - "zleftover:23/91"
        - "zleftover:24/91"
        - "zleftover:25/91"
        - "zleftover:26/91"
        - "zleftover:27/91"
        - "zleftover:28/91"
        - "zleftover:29/91"
        - "zleftover:30/91"
        - "zleftover:31/91"
        - "zleftover:32/91"
        - "zleftover:33/91"
        - "zleftover:34/91"
        - "zleftover:35/91"
        - "zleftover:36/91"
        - "zleftover:37/91"
        - "zleftover:38/91"
        - "zleftover:39/91"
        - "zleftover:40/91"
        - "zleftover:41/91"
        - "zleftover:42/91"
        - "zleftover:43/91"
        - "zleftover:44/91"
        - "zleftover:45/91"
        - "zleftover:46/91"
        - "zleftover:47/91"
        - "zleftover:48/91"
        - "zleftover:49/91"
        - "zleftover:50/91"
        - "zleftover:60/91"
        - "zleftover:61/91"
        - "zleftover:62/91"
        - "zleftover:63/91"
        - "zleftover:64/91"
        - "zleftover:65/91"
        - "zleftover:66/91"
        - "zleftover:67/91"
        - "zleftover:68/91"
        - "zleftover:69/91"
        - "zleftover:70/91"
        - "zleftover:70/91"
        - "zleftover:71/91"
        - "zleftover:72/91"
        - "zleftover:73/91"
        - "zleftover:74/91"
        - "zleftover:75/91"
        - "zleftover:76/91"
        - "zleftover:77/91"
        - "zleftover:78/91"
        - "zleftover:79/91"
        - "zleftover:80/91"
        - "zleftover:80/91"
        - "zleftover:81/91"
        - "zleftover:82/91"
        - "zleftover:83/91"
        - "zleftover:84/91"
        - "zleftover:85/91"
        - "zleftover:86/91"
        - "zleftover:87/91"
        - "zleftover:88/91"
        - "zleftover:89/91"
        - "zleftover:90/91"
        - "zleftover:90/91"
        - "zleftover:91/91"
on:
  push:
  workflow_dispatch:
  schedule: [{cron: '1 0 1,3,5,15,17,19 * *'}]
